"""Extract the pinned official PDF; never infer proprietary card numbering.

Run from repository root. All downloads and outputs stay inside this repository.
"""
import argparse
import hashlib
import json
from pathlib import Path
import urllib.request

import pymupdf

ROOT = Path(__file__).resolve().parents[1]
URL = "https://assets.plickers.com/plickers-cards/PlickersCards_2up_1-63.pdf"
SHA256 = "9b782fd5e62f0f9edd861b0678920caad008d3c005298e201f103330443d3f33"
GOLDEN_IDS = [1, 2, 7, 16, 31, 40, 41, 52, 63]


def rotate_cw(rows):
    return [list(row) for row in zip(*rows[::-1])]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Compare regenerated bytes without changing outputs')
    args = parser.parse_args()
    if pymupdf.VersionBind != '1.27.2.3':
        raise RuntimeError('Install the pinned scripts/requirements.txt before generation')
    pdf_path = ROOT / 'tmp/pdfs/official.pdf'
    pdf_path.parent.mkdir(parents=True, exist_ok=True)
    if not pdf_path.exists():
        pdf_path.write_bytes(urllib.request.urlopen(URL, timeout=60).read())
    if hashlib.sha256(pdf_path.read_bytes()).hexdigest() != SHA256:
        raise ValueError('Official PDF hash changed; review source/layout before updating the pin')
    doc = pymupdf.open(pdf_path)
    assert len(doc) == 32
    references, fixtures = [], []
    outputs = {}
    for card_id in range(1, 64):
        page_index, slot = divmod(card_id - 1, 2)
        page = doc[page_index]
        assert tuple(page.rect) == (0, 0, 612, 792)
        top = 73 + slot * 396
        crop = pymupdf.Rect(181, top, 431, top + 250)
        words = [w for w in page.get_text('words') if slot * 396 <= (w[1] + w[3]) / 2 < (slot + 1) * 396]
        # Validate printed ID and every letter, independently of template matching.
        assert sum(w[4] == str(card_id) for w in words) >= 4
        letters = {}
        for letter in 'ABCD':
            matches = [w for w in words if w[4] == letter]
            assert len(matches) == 1
            w = matches[0]
            dx, dy = (w[0] + w[2]) / 2 - 306, (w[1] + w[3]) / 2 - (top + 125)
            side = (1 if dx > 0 else 3) if abs(dx) > abs(dy) else (2 if dy > 0 else 0)
            letters[side] = letter
        assert len(letters) == 4
        a_side = next(side for side, letter in letters.items() if letter == 'A')
        assert [letters[(a_side + i) % 4] for i in range(4)] == list('ABCD')
        # Sample the actual PDF raster at cell interiors, not a fabricated encoding.
        pix = page.get_pixmap(matrix=pymupdf.Matrix(1, 1), colorspace=pymupdf.csGRAY, clip=crop, alpha=False)
        assert (pix.width, pix.height) == (250, 250)
        samples = pix.samples
        bits = [[int(samples[(y * 50 + 25) * 250 + x * 50 + 25] < 128) for x in range(5)] for y in range(5)]
        for _ in range((-a_side) % 4):
            bits = rotate_cw(bits)
        references.append({'cardId': card_id, 'rows': [''.join(map(str, row)) for row in bits]})
        if card_id in GOLDEN_IDS:
            # Separate 100x100 PDF render, kept in original printed orientation.
            # This is independent of the 5x5 dictionary and decoder rotation code.
            golden = page.get_pixmap(matrix=pymupdf.Matrix(.4, .4), colorspace=pymupdf.csGRAY, alpha=False)
            # Crop from a full-page render with fractional origin to exercise raster edges.
            x, y, size = round(181 * .4), round(top * .4), 100
            data = b''.join(golden.samples[(y + row) * golden.width + x:(y + row) * golden.width + x + size] for row in range(size))
            filename = f'card-{card_id:02d}.pgm'
            payload = b'P5\n100 100\n255\n' + data
            outputs[f'tests/fixtures/{filename}'] = payload
            fixtures.append({'cardId': card_id, 'file': filename, 'page': page_index + 1,
                             'slot': slot, 'topAnswer': letters[0],
                             'answersCW': [letters[(-turn) % 4] for turn in range(4)],
                             'sha256': hashlib.sha256(payload).hexdigest()})
    # All 252 identity/orientation pairs must be distinguishable.
    seen = set()
    for ref in references:
        rows = [list(row) for row in ref['rows']]
        for _ in range(4):
            key = ''.join(''.join(row) for row in rows)
            assert key not in seen, 'Ambiguous reference dictionary'
            seen.add(key)
            rows = rotate_cw(rows)
    metadata = {'sourceUrl': URL, 'sourceSha256': SHA256, 'renderer': f'PyMuPDF {pymupdf.VersionBind}',
                'gridSize': 5, 'canonicalTopAnswer': 'A', 'references': references}
    outputs['src/references.generated.ts'] = (
        '// Generated by scripts/generate_references.py; do not edit. 1 = dark.\n'
        'export const referenceData = ' + json.dumps(metadata, indent=2) + ' as const;\n').encode('utf-8')
    outputs['tests/fixtures/manifest.json'] = (json.dumps({'sourceUrl': URL, 'sourceSha256': SHA256, 'fixtures': fixtures}, indent=2) + '\n').encode('utf-8')
    for relative, data in outputs.items():
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_bytes() != data:
                raise ValueError(f'Regeneration differs: {relative}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print(f'{"Verified" if args.check else "Generated"} 63 references, 252 unique orientations, {len(fixtures)} official PDF golden crops')


if __name__ == '__main__':
    main()
